# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cordslite',
                'doc_host': 'https://AnswerDotAI.github.io',
                'git_url': 'https://github.com/AnswerDotAI/cordslite',
                'lib_path': 'cordslite'},
  'syms': {'cordslite.core': {'cordslite.core.foo': ('core.html#foo', 'cordslite/core.py')}}}
