"""Command routing over REST + Gateway, with voice conveniences

Docs: https://AnswerDotAI.github.io/cordslite/bot.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_bot.ipynb.

# %% auto #0
__all__ = ['Bot']

# %% ../nbs/03_bot.ipynb #4e7d4c90
from .core import *
from .gateway import *
from .voice import *
from fastcore.utils import *

import asyncio

# %% ../nbs/03_bot.ipynb #5fa6efaf
class Bot:
    "Discord bot with command routing"
    def __init__(self, intents, **kw):
        self.dc = DiscordClient(**kw)
        self.gc = GatewayClient(intents, self.dc)
        self.cmds = {}
        self.errors = []
        self._on_err = None

    def cmd(self, f):
        "Register a command handler — function name becomes !name"
        self.cmds[f.__name__] = f
        return f

    async def _on_msg(self, msg):
        if msg.author['id'] == self.gc.user_id: return
        parts = msg.content.split(maxsplit=1)
        if not parts or not parts[0].startswith('!'): return
        name = parts[0][1:]
        if name not in self.cmds: return
        try:
            res = self.cmds[name](msg, parts[1] if len(parts) > 1 else '')
            if asyncio.iscoroutine(res): await res
        except Exception as e:
            self.errors.append(e)
            if self._on_err: await self._on_err(msg, e)

    async def start(self):
        "Connect to gateway and start listening"
        await self.gc.start()
        self.gc.on('MESSAGE_CREATE', self._on_msg)

    async def stop(self): await self.gc.stop()
    def __repr__(self): return f"Bot(cmds={list(self.cmds.keys())})"

# %% ../nbs/03_bot.ipynb #14ea3e49
@patch
def on_error(self:Bot, f):
    self._on_err = f
    return f

# %% ../nbs/03_bot.ipynb #f88c92dd
@patch
async def join_voice(self:Bot, channel):
    "Join a voice channel and return VoiceClient"
    self.vc = VoiceClient(self.gc, channel.guild_id, channel)
    await self.vc.join()
    return self.vc

@patch
async def leave_voice(self:Bot):
    "Leave the current voice channel"
    if self.vc: await self.vc.leave()
    self.vc = None
