# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['depoch', 'evt_typs', 'spf', 'sr', 'DiscordClient', 'DiscordError', 'DiscordObject', 'Guild', 'html_table', 'Channel',
           'Channels', 'Message', 'Messages', 'date2snowflake', 'Attachment', 'User', 'Member', 'Members',
           'GatewayClient', 'Op', 'Event', 'VoiceClient', 'get_ip', 'VoiceUDP', 'decrypt_pkt', 'silence', 'Bot']

# %% ../nbs/00_core.ipynb #9868997a
from datetime import datetime, timedelta, timezone
from fasthtml.common import *
from fastcore.meta import *
from fastcore.utils import *
from nacl.bindings import crypto_aead_xchacha20poly1305_ietf_decrypt as xchacha_decrypt

import asyncio,ffmpeg,httpx,json,opuslib_next,os,random,re,socket,time
import websockets.asyncio.client

# %% ../nbs/00_core.ipynb #d9e0f6cf
class DiscordClient:
    def __init__(self, token=None, user_token=None, name='cordslite', ver='0.1'):
        self.token = token or os.environ['DISCORD_BOT_TOKEN']
        self.user_token = user_token or os.environ.get('DISCORD_USER_TOKEN')
        self.base_url = 'https://discord.com/api/v10'
        self.headers = {'Authorization': f'Bot {self.token}', 'User-Agent': f'DiscordBot ({name}, {ver})'}
        self.cli = httpx.AsyncClient(base_url=self.base_url, headers=self.headers)


# %% ../nbs/00_core.ipynb #cb503de5
class DiscordError(Exception):
    def __init__(self, code, msg, status): self.code,self.msg,self.status = code,msg,status
    def __str__(self): return f"DiscordError({self.status}): [{self.code}] {self.msg}"

@patch
async def _req(self:DiscordClient, method, path, data=None, files=None, use_user=False, **kw):
    kw = filter_values(kw, negate(is_(None)))
    if method=='GET': params,json = kw,None
    else: params,json = None,kw
    if use_user:
        if not self.user_token: raise ValueError("User token required for this operation")
        kw['headers'] = {'Authorization': self.user_token}
    r = await self.cli.request(method, path, data=data, files=files, params=params, json=json)
    if r.status_code == 429:
        await asyncio.sleep(float(r.headers.get('Retry-After', 1))+0.1)
        return await self._req(method, path, use_user=use_user, **kw)
    if r.status_code >= 400:
        try: d = r.json()
        except Exception: d = {}
        raise DiscordError(d.get('code', 0), d.get('message', r.text[:200]), r.status_code)
    if r.status_code == 204: return 'done'
    try: return r.json()
    except Exception as e: raise Exception(f"Failed to parse response: {r.text}; {e}")

# %% ../nbs/00_core.ipynb #fafdfb4b
class DiscordObject(AttrDict):
    def __init__(self, data, client):
        super().__init__(data)
        self._client = getattr(client, '_client', client)
    
    async def __call__(self, meth, path, **kw): return await self._client._req(meth, path, **kw)
    def obj(self, nm, d): return globals()[nm](d, self)
    def coll(self, nm, ds): return globals()[nm+'s'](self.obj(nm,d) for d in ds)

# %% ../nbs/00_core.ipynb #e22aa99c
class Guild(DiscordObject):
    def __repr__(self): return f"Guild(id={self.id}, name={self.name!r})"

# %% ../nbs/00_core.ipynb #0aa23bb9
@patch
async def guild(self:DiscordClient, guild_id):
    return Guild(await self._req('GET', f'/guilds/{guild_id}'), self)

# %% ../nbs/00_core.ipynb #523e4a31
def html_table(items, hdrs, fn):
    if not items: return ""
    rows = (Tr(map(Td, fn(o))) for o in items)
    return to_xml(Table(Thead(Tr(map(Th, hdrs))), Tbody(rows), cls="prose"))

# %% ../nbs/00_core.ipynb #ba94ea4a
class Channel(DiscordObject):
    @property
    async def guild(self):
        if not hasattr(self, '_gld'): self._gld = await self._client.guild(self.guild_id)
        return self._gld
    def __repr__(self): return f"Channel(id={self.id}, name={self.name!r}, type={self.type})"

class Channels(list):
    def _repr_html_(self): return html_table(self, ("ID", "Name", "Type"), lambda c: (c.id, c.name, c.type))

# %% ../nbs/00_core.ipynb #8cdfc370
@patch
async def channels(self:Guild, limit=None):
    data = await self('GET', f'/guilds/{self.id}/channels')
    if limit: data = data[:limit]
    return self.coll('Channel', data)

# %% ../nbs/00_core.ipynb #eded7bca
@patch
async def channel(self:DiscordClient, channel_id):
    return Channel(await self._req('GET', f'/channels/{channel_id}'), self)

# %% ../nbs/00_core.ipynb #461bcb8b
class Message(DiscordObject):
    def __init__(self, data, dobj):
        super().__init__(data, dobj)
        self.raw_content = self.content
        mentions = {m['id']: m['username'] for m in data.get('mentions', [])}
        def repl(m): return f"@{mentions.get(m.group(1), 'unknown')}"
        self['content'] = re.sub(r'<@!?(\d+)>', repl, self.content)

    def __repr__(self): 
        author = self.author['username']
        preview = self.content[:30] + '…' if len(self.content) > 30 else self.content
        return f"Message(id={self.id}, author={author!r}, content={preview!r})"

    @property
    async def channel(self):
        if not hasattr(self, '_ch'): self._ch = Channel(await self('GET', f'/channels/{self.channel_id}'), self._client)
        return self._ch

# %% ../nbs/00_core.ipynb #666652da
class Messages(list):
    def _repr_html_(self):
        return html_table(self, ("ID", "Author", "Content", "Date"),
            lambda m: (m.id, m.author['username'], m.content[:50], m.timestamp[:10]))

# %% ../nbs/00_core.ipynb #a571a2d5
@patch
async def messages(self:Channel, limit=50):
    data = await self('GET', f'/channels/{self.id}/messages', limit=limit)
    return self.coll('Message', reversed(data))

# %% ../nbs/00_core.ipynb #e589948c
depoch = 1420070400000
def date2snowflake(date_str):
    "Convert 'YYYY-MM-DD' to a Discord snowflake ID"
    dt = datetime.fromisoformat(date_str).replace(tzinfo=timezone.utc)
    return str(int((dt.timestamp() * 1000 - depoch) * (2**22)))

@patch
async def search(self:Guild, content=None, author_id=None, channel_id=None, mentions=None,
                 has=None, before=None, after=None, pinned=None, sort_by=None, sort_order=None,
                 offset=None, limit=None, use_user=False):
    "Search guild messages. `before`/`after` accept 'YYYY-MM-DD' strings or snowflake IDs."
    if before and not str(before).isdigit(): before = date2snowflake(before)
    if after and not str(after).isdigit(): after = date2snowflake(after)
    r = await self('GET', f'/guilds/{self.id}/messages/search', use_user=use_user,
        content=content, author_id=author_id, channel_id=channel_id,
        mentions=mentions, has=has, min_id=after, max_id=before, pinned=pinned,
        sort_by=sort_by, sort_order=sort_order, offset=offset, limit=limit)
    return self.coll('Message', [m[0] for m in r['messages']])

# %% ../nbs/00_core.ipynb #44642992
@patch
async def find_member(self:Guild, name):
    "Search guild members by name/nick, return first match's user ID or None"
    data = await self( 'GET', f'/guilds/{self.id}/members/search', query=name, limit=1)
    return data[0]['user']['id'] if data else None

# %% ../nbs/00_core.ipynb #eeaf8a6f
@patch(as_prop=True)
async def members(self:Guild):
    "List all guild members' display names (nick > global_name > username)"
    data = await self('GET', f'/guilds/{self.id}/members', limit=1000)
    return [m.get('nick') or m['user'].get('global_name') or m['user']['username'] for m in data]

# %% ../nbs/00_core.ipynb #cc5bd70d
@patch
async def send(self:Channel, content='', files=None, reply_id=None):
    "Send a message with optional file attachments"
    path = f'/channels/{self.id}/messages'
    mref = {'message_id': reply_id} if reply_id else None
    payload = filter_values(dict(content=content, message_reference=mref), negate(is_(None)))
    fs = [('files[%d]' % i, (f.name, f.read_bytes(), None)) for i,f in enumerate(map(Path, listify(files)))]
    r = await self('POST', path, data={'payload_json': json.dumps(payload)}, files=fs)
    return Message(r, self)

# %% ../nbs/00_core.ipynb #9e14fc6c
@patch
@delegates(Guild.search, but=['channel_id'])
async def search(self:Channel, **kwargs): return await (await self.guild).search(channel_id=self.id, **kwargs)

# %% ../nbs/00_core.ipynb #fd998c99
class Attachment(DiscordObject):
    async def fetch(self): return (await self._client.cli.get(self.url)).content
    def __repr__(self): return f"Attachment(filename={self.filename!r}, size={self.size}, type={self.content_type})"
    def _repr_html_(self):
        if self.content_type.startswith('image/'):
            return f'<img src="{self.url}" style="max-width:400px"><br><small>{self.filename} ({self.size:,}B)</small>'
        return f'<code>{self.filename}</code> ({self.content_type}, {self.size:,}B)'

@patch(as_prop=True)
def attachments(self:Message): return [Attachment(a, self._client) for a in self.get('attachments', [])]

# %% ../nbs/00_core.ipynb #acf92bc2
@patch
async def create_dm(self:DiscordClient, user_id):
    r = await self._req('POST', '/users/@me/channels', recipient_id=user_id)
    return Channel(r, self)

# %% ../nbs/00_core.ipynb #66bb1704
class User(DiscordObject):
    def __repr__(self): return f"User(id={self.id}, username={self.username!r})"

class Member(DiscordObject):
    def __repr__(self):
        name = self.nick or self.user['username']
        return f"Member(id={self.user['id']}, name={name!r}, joined={self.joined_at[:10]})"

class Members(list):
    def _repr_html_(self): return html_table(self, ("ID", "Name", "Joined", "Roles"), lambda m: (m.user['id'], m.nick or m.user['username'], m.joined_at[:10], len(m.roles)))

@patch
async def members(self:Guild, limit=100):
    data = await self('GET', f'/guilds/{self.id}/members', limit=limit)
    return self.coll('Member', data)

# %% ../nbs/00_core.ipynb #4687437a
@patch
async def search_all(self:Guild, limit=500, delay=1.0, max_age_days=None, show=False, **kwargs):
    "Paginated search returning up to `limit` messages"
    all_msgs, offset = [], 0
    while len(all_msgs) < limit:
        msgs = await self.search(offset=offset, limit=25, **kwargs)
        if not msgs: break
        if max_age_days is not None:
            cutoff = datetime.now(timezone.utc) - timedelta(days=max_age_days)
            msgs = [m for m in msgs if datetime.fromisoformat(m.timestamp) > cutoff]
        all_msgs.extend(msgs)
        offset += 25
        if show: print(f'Fetched {len(msgs)} more')
        if len(msgs) < 25: break
        await asyncio.sleep(delay)
    return Messages(all_msgs[:limit])

@patch
@delegates(Guild.search_all, but=['channel_id'])
async def search_all(self:Channel, **kwargs):
    gld = await self.guild
    return await gld.search_all(channel_id=self.id, **kwargs)

# %% ../nbs/00_core.ipynb #beead147
@patch
async def delete(self:Message):
    "Delete this message"
    return await self('DELETE', f'/channels/{self.channel_id}/messages/{self.id}')

@patch
async def delete_message(self:Channel, message_id):
    "Delete a message by ID"
    return await self('DELETE', f'/channels/{self.id}/messages/{message_id}')

@patch
async def bulk_delete(self:Channel, message_ids):
    "Bulk delete messages (must be <14 days old)"
    return await self('POST', f'/channels/{self.id}/messages/bulk-delete', messages=[str(i) for i in message_ids])

# %% ../nbs/00_core.ipynb #1834fc2f
@patch
async def create_thread(self:Message, name):
    "Create a thread from this message"
    r = await self('POST', f'/channels/{self.channel_id}/messages/{self.id}/threads', name=name)
    return Channel(r, self)

@patch
async def thread(self:DiscordClient, thread_id):
    "Fetch a thread (which is a Channel)"
    return Channel(await self._req('GET', f'/channels/{thread_id}'), self)

# %% ../nbs/00_core.ipynb #05498e5a
@patch
async def _del_rotating(self:Channel, message_ids, delay=0.5, show=False):
    if show: print(f'Deleting {len(message_ids)} messages...')
    for i,mid in enumerate(message_ids):
        use_user = i % 2 == 1 and bool(self._client.user_token)
        await self('DELETE', f'/channels/{self.id}/messages/{mid}', use_user=use_user)
        await asyncio.sleep(delay)
        if show: print('.', end='', flush=True)
    return len(message_ids)

@patch
async def search_and_delete_all(self:Channel, content, delay=2, show=False, **kwargs):
    "Bulk delete recent msgs, individually delete older ones"
    assert content, "Must include content to search for"
    cutoff = datetime.now(timezone.utc) - timedelta(days=13)
    gld = await self.guild
    msgs = await gld.search_all(content=content, channel_id=self.id, show=show, **kwargs)
    recent = [m for m in msgs if datetime.fromisoformat(m.timestamp) > cutoff]
    old = [m for m in msgs if datetime.fromisoformat(m.timestamp) <= cutoff]
    for i in range(0, len(recent), 20):
        ms = recent[i:i+20]
        await self.bulk_delete([m.id for m in ms])
        if show: print(f'Bulk deleted {len(ms)}')
        await asyncio.sleep(delay)
    if old: await self._del_rotating([m.id for m in old], show=show, delay=delay)
    return len(msgs)

# %% ../nbs/00_core.ipynb #a301c00c
class GatewayClient:
    def __init__(self, intents, client, token=None):
        self.intents,self.dc = intents,client
        self.token = token or os.environ['DISCORD_BOT_TOKEN']
        self.ws = self.hb_int = self.session_id = self.seq = None
        self.running = False
        gw_info = httpx.get(f'{client.base_url}/gateway/bot', headers={'Authorization': f'Bot {self.token}'}).json()
        if 'url' not in gw_info: raise ConnectionError(f"Gateway auth failed: {gw_info.get('message', gw_info)}")
        self.url = f"{gw_info['url']}?v=10&encoding=json"
        self.handlers = {'READY': self.on_rdy}
    
    async def on_rdy(self, evt):
        self.session_id, self.user_id, = evt['session_id'], evt['user']['id']
        self.resume_url = evt.get('resume_gateway_url', self.url) + '?v=10&encoding=json'
        
    def __repr__(self): return f"GatewayClient({self.intents=}, {self.url=})"

# %% ../nbs/00_core.ipynb #bcdec263
class Op(AttrDict):
    def __repr__(self): return f"Op(op={self.op}, d={self.d})"
    @classmethod
    def identify(cls, token, intents):
        d = AttrDict(token=token, intents=intents, properties=dict(os='linux',browser='discord_wrapper', device='discord_wrapper'))
        return cls(op=2, d=d)
    @classmethod
    def heartbeat(cls, seq): return cls(op=1, d=seq)
    @classmethod
    def resume(cls, token, session_id, seq): return cls(op=6, d=AttrDict(token=token, session_id=session_id, seq=seq))

# %% ../nbs/00_core.ipynb #6932c93e
evt_typs = {'MESSAGE_CREATE': Message,
            'MESSAGE_UPDATE': Message,
            'MESSAGE_DELETE': Message,
            'GUILD_CREATE': Guild,
            'CHANNEL_CREATE': Channel}

class Event(DiscordObject):
    def __init__(self, data, client):
        super().__init__(data, client)
        typ = evt_typs.get(self.t)
        self.d = typ(self.d, client) if typ else self.d
    @property
    def type(self): return self.t
    @property
    def seq(self): return self.s
    def __repr__(self): return f"Event({self.op=}, {self.type=}, {self.seq=})"

# %% ../nbs/00_core.ipynb #927372d6
@patch
async def send(self:websockets.asyncio.client.ClientConnection, msg, **kw):
    if isinstance(msg, dict): msg = json.dumps(msg)
    return await self._orig_send(msg, **kw)

# %% ../nbs/00_core.ipynb #b55577b6
@patch
async def recv_evt(self:GatewayClient):
    evt = Event(json.loads(await self.ws.recv()), self.dc)
    if evt.op == 0 and evt.seq: self.seq = evt.seq
    return evt

# %% ../nbs/00_core.ipynb #ce969a6d
@patch
def on(self:GatewayClient, event_type, handler): self.handlers[event_type] = handler

# %% ../nbs/00_core.ipynb #fe369f1b
@patch
async def _hb(self:GatewayClient):
    await asyncio.sleep(self.hb_int / 1_000 * random.random()) # jitter
    while self.running:
        self._got_ack = False
        await self.ws.send(Op.heartbeat(self.seq))
        await asyncio.sleep(self.hb_int / 1_000)
        if not self._got_ack: return await self.ws.close(code=4000)

# %% ../nbs/00_core.ipynb #89929987
@patch
async def _reconnect(self:GatewayClient):
    await self.ws.close(code=4000)
    self.ws = await websockets.connect(self.resume_url)

# %% ../nbs/00_core.ipynb #9fc42e1a
@patch
async def _listen(self:GatewayClient):
    while self.running:
        try: evt = await self.recv_evt()
        except Exception as e:
            print(e)
            await self._reconnect()
            continue
        if evt.op == 10:
            self.hb_int = evt.d['heartbeat_interval']
            if hasattr(self, '_hb_task') and self._hb_task: self._hb_task.cancel()
            self._hb_task = asyncio.create_task(self._hb())
            if hasattr(self, 'resume_url'): await self.ws.send(Op.resume(self.token, self.session_id, self.seq))
            else: await self.ws.send(Op.identify(self.token, self.intents))
        elif evt.op == 0 and evt.type in self.handlers: asyncio.create_task(self.handlers[evt.type](evt.d))
        elif evt.op == 11: self._got_ack = True
        elif evt.op == 1: await self.ws.send(Op.heartbeat(self.seq))
        elif evt.op == 7: await self._reconnect()

# %% ../nbs/00_core.ipynb #13b642d7
@patch
async def start(self:GatewayClient):
    self.running = True
    self.ws = await websockets.connect(self.url)
    self._listen_task = asyncio.create_task(self._listen())

# %% ../nbs/00_core.ipynb #bef72576
@patch
async def stop(self:GatewayClient):
    self.running = False
    for t in (self._hb_task, self._listen_task):
        if t: t.cancel()
    if self.ws: await self.ws.close()

# %% ../nbs/00_core.ipynb #9643482d
class VoiceClient:
    def __init__(self, gateway, channel):
        self.gw, self.ch = gateway, channel
        self.ws,self.udp,self.hb_int,self.ssrc,self.secret = None,None,None,None,None
        self.running,self.v_seq,self.loop = False,-1,None
    def __repr__(self): return f'VoiceClient({self.ch=}, {self.running=})'

# %% ../nbs/00_core.ipynb #aad5881e
@patch(cls_method=True)
def voice_state(cls:Op, guild_id, channel_id):
    return cls(op=4, d=AttrDict(guild_id=guild_id, channel_id=channel_id, self_mute=False, self_deaf=False))
@patch(cls_method=True)
def voice_identify(cls:Op, server_id, user_id, session_id, token):
    return cls(op=0, d=AttrDict(server_id=server_id, user_id=user_id, session_id=session_id, token=token))
@patch(cls_method=True)
def select_protocol(cls:Op, ip, port, mode='aead_xchacha20_poly1305_rtpsize'):
    return cls(op=1, d=AttrDict(protocol='udp', data=dict(address=ip, port=port, mode=mode)))
@patch(cls_method=True)
def speaking(cls:Op, ssrc, speaking=0):
    return cls(op=5, d=AttrDict(speaking=speaking, delay=0, ssrc=ssrc))
@patch(cls_method=True)
def voice_heartbeat(cls:Op, seq_ack=-1):
    return cls(op=3, d=AttrDict(t=int(time.time() * 1000), seq_ack=seq_ack))

# %% ../nbs/00_core.ipynb #b770e806
@patch
async def _vhb(self:VoiceClient):
    await asyncio.sleep(self.hb_int / 1_000 * random.random())
    while self.running:
        await self.ws.send(Op.voice_heartbeat(self.v_seq))
        await asyncio.sleep(self.hb_int / 1_000)

@patch
async def _connect(self:VoiceClient):
    self.v_srv = {}
    srv_rdy = asyncio.Event()
    async def on_vs(data):
        self.v_srv.update(data)
        srv_rdy.set()
    self.gw.on('VOICE_SERVER_UPDATE', on_vs)
    await self.gw.ws.send(Op.voice_state(self.ch.guild_id, self.ch.id))
    await srv_rdy.wait()
    self.ws = await websockets.connect(f"wss://{self.v_srv['endpoint']}?v=8")
    hello = json.loads(await self.ws.recv())
    self.hb_int = hello['d']['heartbeat_interval']
    self.running = True
    asyncio.create_task(self._vhb())
    await self.ws.send(Op.voice_identify(self.ch.guild_id, self.gw.user_id, self.gw.session_id, self.v_srv['token']))
    self.v_rdy = json.loads(await self.ws.recv())
    self.ssrc = self.v_rdy['d']['ssrc']

# %% ../nbs/00_core.ipynb #db1dc74b
async def get_ip(trans, proto, ssrc):
    pkt = bytearray(74)
    pkt[0:2],pkt[2:4],pkt[4:8] = (1).to_bytes(2,'big'),(70).to_bytes(2,'big'),ssrc.to_bytes(4,'big')
    trans.sendto(pkt)
    r = await proto.packets.get()
    return r[8:72].decode('utf-8').rstrip('\x00'), int.from_bytes(r[72:74], 'big')

# %% ../nbs/00_core.ipynb #c41a0035
class VoiceUDP(asyncio.DatagramProtocol):
    def __init__(self): self.packets = asyncio.Queue()
    def datagram_received(self, data, addr): self.packets.put_nowait(data)

# %% ../nbs/00_core.ipynb #517be983
@patch
async def _udp(self:VoiceClient):
    udp_ip, udp_port = self.v_rdy['d']['ip'], self.v_rdy['d']['port']
    self.loop = asyncio.get_running_loop()
    self.trans, self.proto = await self.loop.create_datagram_endpoint(VoiceUDP, remote_addr=(udp_ip, udp_port))
    ip, port = await get_ip(self.trans, self.proto, self.ssrc)
    await self.ws.send(Op.select_protocol(ip, port))
    desc = json.loads(await self.ws.recv())
    while desc['op'] != 4: desc = json.loads(await self.ws.recv())
    self.secret = bytes(desc['d']['secret_key'])
    await self.ws.send(Op.speaking(self.ssrc))

# %% ../nbs/00_core.ipynb #694c944e
@patch
async def join(self:VoiceClient):
    await self._connect()
    await self._udp()
    print(f"Voice ready!")

# %% ../nbs/00_core.ipynb #a9db9c12
def decrypt_pkt(pkt, secret):
    csrc_cnt = pkt[0] & 0x0F
    hdr_sz = 12 + csrc_cnt * 4 + (4 if pkt[0] & 0x10 else 0)
    nonce = bytearray(24) # only use 4, but pad to 24 bytes as expected by the cipher
    nonce[:4] = pkt[-4:]
    data, hdr, nonce = bytes(pkt[hdr_sz:-4]), bytes(pkt[:hdr_sz]), bytes(nonce)
    decrypted = xchacha_decrypt(data, hdr, nonce, bytes(secret))
    ext_sz = int.from_bytes(pkt[14:16], 'big') * 4 # extension data size in bytes
    return decrypted[ext_sz:]

# %% ../nbs/00_core.ipynb #c06edb1d
spf = 960
sr = 48_000
def silence(n_smpls:int): return b'\x00' * (n_smpls * 2) # 2 bytes per sample (s16le)

@patch
def _get_proc(self:VoiceClient, ssrc):
    if ssrc not in self._procs:
        pth = str(self._rec_path.with_stem(f"{self._rec_path.stem}_{ssrc}"))
        proc = (ffmpeg.input('pipe:', f='s16le', ar=sr, ac=1)
                      .output(pth).overwrite_output()
                      .run_async(pipe_stdin=True, quiet=True))
        proc.stdin.write(silence(int((time.time() - self._rec_start) * sr)))
        self._procs[ssrc] = proc
    return self._procs[ssrc]

@patch
def _write_audio(self:VoiceClient, ssrc, ts, data):
    proc = self._get_proc(ssrc)
    # Fill silence gaps
    if ssrc in self._last_ts:
        gap = ts - self._last_ts[ssrc] - spf
        if gap > 0: proc.stdin.write(silence(gap))
    self._last_ts[ssrc] = ts
    proc.stdin.write(self._decoders[ssrc].decode(data, spf))

@patch
async def _recv_audio(self:VoiceClient):
    while self._recording:
        try:
            pkt = await asyncio.wait_for(self.proto.packets.get(), timeout=0.1)
            if pkt[1] != 0x78: continue # filter out RTP non-voice packets 
            ssrc = int.from_bytes(pkt[8:12], 'big')
            ts = int.from_bytes(pkt[4:8], 'big')
            if ssrc not in self._decoders: self._decoders[ssrc] = opuslib_next.Decoder(sr, 1)
            if data := decrypt_pkt(pkt, self.secret): self._write_audio(ssrc, ts, data)
        except asyncio.TimeoutError: continue

# %% ../nbs/00_core.ipynb #b17c0541
@patch
def start_recording(self:VoiceClient, path='recording.mp3'):
    while not self.proto.packets.empty(): self.proto.packets.get_nowait()
    self._rec_path,self._decoders,self._procs,self._last_ts = Path(path),{},{},{}
    self._rec_start = time.time()
    self._recording = True
    self._rec_task = asyncio.create_task(self._recv_audio())
    return path

@patch
def stop_recording(self:VoiceClient):
    self._recording = False
    self._rec_task.cancel()
    for p in self._procs.values(): p.communicate()
    return [str(self._rec_path.with_stem(f"{self._rec_path.stem}_{ssrc}")) for ssrc in self._procs]

# %% ../nbs/00_core.ipynb #a79084f1
@patch
async def leave(self:VoiceClient):
    self.running = False
    if self.ws: await self.ws.close()
    if self.trans: self.trans.close()
    await self.gw.ws.send(Op.voice_state(self.ch.guild_id, None))

# %% ../nbs/00_core.ipynb #84855115
class Bot:
    "Discord bot with command routing"
    def __init__(self, intents, **kw):
        self.dc = DiscordClient(**kw)
        self.gc = GatewayClient(intents, self.dc)
        self.cmds = {}
        self.errors = []
        self._on_err = None

    def cmd(self, f):
        "Register a command handler — function name becomes !name"
        self.cmds[f.__name__] = f
        return f

    async def _on_msg(self, msg):
        if msg.author['id'] == self.gc.user_id: return
        parts = msg.content.split(maxsplit=1)
        if not parts or not parts[0].startswith('!'): return
        name = parts[0][1:]
        if name not in self.cmds: return
        try:
            res = self.cmds[name](msg, parts[1] if len(parts) > 1 else '')
            if asyncio.iscoroutine(res): await res
        except Exception as e:
            self.errors.append(e)
            if self._on_err: await self._on_err(msg, e)

    async def start(self):
        "Connect to gateway and start listening"
        await self.gc.start()
        self.gc.on('MESSAGE_CREATE', self._on_msg)

    async def stop(self): await self.gc.stop()
    def __repr__(self): return f"Bot(cmds={list(self.cmds.keys())})"

# %% ../nbs/00_core.ipynb #93b8b465
@patch
def on_error(self:Bot, f):
    self._on_err = f
    return f

# %% ../nbs/00_core.ipynb #23a771be
@patch
async def join_voice(self:Bot, channel):
    "Join a voice channel and return VoiceClient"
    self.vc = VoiceClient(self.gc, channel)
    await self.vc.join()
    return self.vc

@patch
async def leave_voice(self:Bot):
    "Leave the current voice channel"
    if self.vc: await self.vc.leave()
    self.vc = None
