"""Docs: https://AnswerDotAI.github.io/cordslite/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['DISCORD_WEB', 'depoch', 'DiscordClient', 'DiscordError', 'DiscordObject', 'Guild', 'html_table', 'Channel',
           'Channels', 'Guilds', 'Message', 'Messages', 'date2snowflake', 'Attachment', 'User', 'Member', 'Members',
           'lbl', 'Webhook', 'Webhooks']

# %% ../nbs/00_core.ipynb #9868997a
from collections import defaultdict
from datetime import datetime, timedelta, timezone
from fastcore.meta import *
from fastcore.utils import *
from fasthtml.common import *

import asyncio,httpx,json,os,re


# %% ../nbs/00_core.ipynb #d9e0f6cf
class DiscordClient:
    def __init__(self, token=None, user_token=None, name='cordslite', ver='0.1'):
        self.token = token or os.environ['DISCORD_BOT_TOKEN']
        self.user_token = user_token or os.environ.get('DISCORD_USER_TOKEN')
        self.base_url = 'https://discord.com/api/v10'
        self.headers = {'Authorization': f'Bot {self.token}', 'User-Agent': f'DiscordBot ({name}, {ver})'}
        self.cli = httpx.AsyncClient(base_url=self.base_url, headers=self.headers)


# %% ../nbs/00_core.ipynb #cb503de5
class DiscordError(Exception):
    def __init__(self, code, msg, status): self.code,self.msg,self.status = code,msg,status
    def __str__(self): return f"DiscordError({self.status}): [{self.code}] {self.msg}"

@patch
async def _req(self:DiscordClient, method, path, data=None, files=None, use_user=False, **kw):
    kw = filter_values(kw, negate(is_(None)))
    if method=='GET': params,json = kw,None
    else: params,json = None,kw
    if use_user:
        if not self.user_token: raise ValueError("User token required for this operation")
        kw['headers'] = {'Authorization': self.user_token}
    r = await self.cli.request(method, path, data=data, files=files, params=params, json=json)
    if r.status_code == 429:
        await asyncio.sleep(float(r.headers.get('Retry-After', 1))+0.1)
        return await self._req(method, path, use_user=use_user, **kw)
    if r.status_code >= 400:
        try: d = r.json()
        except Exception: d = {}
        raise DiscordError(d.get('code', 0), d.get('message', r.text[:200]), r.status_code)
    if r.status_code == 204: return 'done'
    try: return r.json()
    except Exception as e: raise Exception(f"Failed to parse response: {r.text}; {e}")

# %% ../nbs/00_core.ipynb #fafdfb4b
class DiscordObject(AttrDict):
    def __init__(self, data, client):
        super().__init__(data)
        self._client = getattr(client, '_client', client)
        self._parent = client
    
    async def __call__(self, meth, path, **kw): return await self._client._req(meth, path, **kw)
    def obj(self, nm, d): return globals()[nm](d, self)
    def coll(self, nm, ds): return globals()[nm+'s'](self.obj(nm,d) for d in ds)

# %% ../nbs/00_core.ipynb #e22aa99c
class Guild(DiscordObject):
    def __repr__(self): return f"Guild(id={self.id}, name={self.name!r})"

# %% ../nbs/00_core.ipynb #0aa23bb9
@patch
async def guild(self:DiscordClient, guild_id):
    return Guild(await self._req('GET', f'/guilds/{guild_id}'), self)

# %% ../nbs/00_core.ipynb #523e4a31
def html_table(items, hdrs, fn):
    if not items: return ""
    rows = (Tr(map(Td, fn(o))) for o in items)
    return to_xml(Table(Thead(Tr(map(Th, hdrs))), Tbody(rows), cls="prose"))

class Channel(DiscordObject):
    @property
    async def guild(self):
        if not hasattr(self, '_gld'): self._gld = await self._client.guild(self.guild_id)
        return self._gld
    def __repr__(self): return f"Channel(id={self.id}, name={self.name!r}, type={self.type})"

class Channels(list):
    def _repr_html_(self): return html_table(self, ("ID", "Name", "Type"), lambda c: (c.id, c.name, c.type))

@patch
async def channels(self:Guild, limit=None):
    data = await self('GET', f'/guilds/{self.id}/channels')
    if limit: data = data[:limit]
    return self.coll('Channel', data)

# %% ../nbs/00_core.ipynb #eded7bca
@patch
async def channel(self:DiscordClient, channel_id):
    return Channel(await self._req('GET', f'/channels/{channel_id}'), self)

# %% ../nbs/00_core.ipynb #b28c1392
class Guilds(list):
    def _repr_html_(self): return html_table(self, ("ID", "Name"), lambda g: (g.id, g.name))

@patch
async def guilds(self:DiscordClient, limit=None):
    "List the guilds the bot is a member of"
    data = await self._req('GET', '/users/@me/guilds', limit=limit)
    return Guilds(Guild(d, self) for d in data)

# %% ../nbs/00_core.ipynb #461bcb8b
class Message(DiscordObject):
    def __init__(self, data, dobj):
        super().__init__(data, dobj)
        self.raw_content = self.content
        mentions = {m['id']: m['username'] for m in data.get('mentions', [])}
        def repl(m): return f"@{mentions.get(m.group(1), 'unknown')}"
        self['content'] = re.sub(r'<@!?(\d+)>', repl, self.content)

    def __repr__(self): 
        author = self.author['username']
        preview = self.content[:30] + '…' if len(self.content) > 30 else self.content
        return f"Message(id={self.id}, author={author!r}, content={preview!r})"

    @property
    async def channel(self):
        if not hasattr(self, '_ch'): self._ch = Channel(await self('GET', f'/channels/{self.channel_id}'), self._client)
        return self._ch

class Messages(list):
    def _repr_html_(self):
        return html_table(self, ("ID", "Author", "Content", "Date"),
            lambda m: (m.id, m.author['username'], m.content[:50], m.timestamp[:10]))

@patch
async def messages(self:Channel, limit=50, before=None, after=None, around=None):
    "Fetch channel messages. `before`, `after`, and `around` are mutually exclusive message IDs."
    if sum(x is not None for x in [before, after, around]) > 1:
        raise ValueError("Pass only one of `before`, `after`, or `around`")

    def mid(x): return x.id if isinstance(x, Message) else x
    data = await self('GET', f'/channels/{self.id}/messages',
                      limit=limit, before=mid(before), after=mid(after), around=mid(around))
    return self.coll('Message', reversed(data))

# %% ../nbs/00_core.ipynb #a0695db1
@patch
async def before(self:Message, limit=5):
    "Fetch messages before this message in the same channel/thread."
    return await (await self.channel).messages(before=self, limit=limit)

@patch
async def after(self:Message, limit=5):
    "Fetch messages after this message in the same channel/thread."
    return await (await self.channel).messages(after=self, limit=limit)

@patch
async def around(self:Message, limit=11):
    "Fetch messages around this message in the same channel/thread."
    return await (await self.channel).messages(around=self, limit=limit)

# %% ../nbs/00_core.ipynb #4a8fbfdb
DISCORD_WEB = 'https://discord.com/channels'

@patch(as_prop=True)
def url(self:Guild): return f'{DISCORD_WEB}/{self.id}'

@patch(as_prop=True)
def url(self:Channel): return f'{DISCORD_WEB}/{self.guild_id}/{self.id}'

@patch(as_prop=True)
def url(self:Message):
    gid = self.get('guild_id') or self._parent.get('guild_id') or self._parent.id
    return f'{DISCORD_WEB}/{gid}/{self.channel_id}/{self.id}'

# %% ../nbs/00_core.ipynb #e589948c
depoch = 1420070400000

def date2snowflake(date_str):
    "Convert 'YYYY-MM-DD' to a Discord snowflake ID"
    dt = datetime.fromisoformat(date_str).replace(tzinfo=timezone.utc)
    return str(int((dt.timestamp() * 1000 - depoch) * (2**22)))

@patch
async def search(self:Guild, content=None, author_id=None, channel_id=None, mentions=None,
                 has=None, before=None, after=None, pinned=None, sort_by=None, sort_order=None,
                   offset=None, limit=None, use_user=False, nothread:bool=True):
    "Search guild messages. `before`/`after` accept 'YYYY-MM-DD' strings or snowflake IDs."
    if before and not str(before).isdigit(): before = date2snowflake(before)
    if after and not str(after).isdigit(): after = date2snowflake(after)
    r = await self('GET', f'/guilds/{self.id}/messages/search', use_user=use_user,
        content=content, author_id=author_id, channel_id=channel_id,
        mentions=mentions, has=has, min_id=after, max_id=before, pinned=pinned,
        sort_by=sort_by, sort_order=sort_order, offset=offset, limit=limit)
    msgs = [m for m in [m[0] for m in r['messages']]
        if not (nothread and channel_id and m['channel_id'] != channel_id)]
    return self.coll('Message', msgs)

# %% ../nbs/00_core.ipynb #44642992
@patch
async def find_member(self:Guild, name):
    "Search guild members by name/nick, return first match's user ID or None"
    data = await self( 'GET', f'/guilds/{self.id}/members/search', query=name, limit=1)
    return data[0]['user']['id'] if data else None

# %% ../nbs/00_core.ipynb #cc5bd70d
@patch
async def send(self:Channel, content='', files=None, reply_id=None):
    "Send a message with optional file attachments"
    path = f'/channels/{self.id}/messages'
    mref = {'message_id': reply_id} if reply_id else None
    payload = filter_values(dict(content=content, message_reference=mref), negate(is_(None)))
    fs = [('files[%d]' % i, (f.name, f.read_bytes(), None)) for i,f in enumerate(map(Path, listify(files)))]
    r = await self('POST', path, data={'payload_json': json.dumps(payload)}, files=fs)
    return Message(r, self)

# %% ../nbs/00_core.ipynb #9e14fc6c
@patch
@delegates(Guild.search, but=['channel_id'])
async def search(self:Channel, **kwargs): return await (await self.guild).search(channel_id=self.id, **kwargs)

# %% ../nbs/00_core.ipynb #fd998c99
class Attachment(DiscordObject):
    async def fetch(self): return (await self._client.cli.get(self.url)).content
    def __repr__(self): return f"Attachment(filename={self.filename!r}, size={self.size}, type={self.content_type})"
    def _repr_html_(self):
        if self.content_type.startswith('image/'):
            return f'<img src="{self.url}" style="max-width:400px"><br><small>{self.filename} ({self.size:,}B)</small>'
        return f'<code>{self.filename}</code> ({self.content_type}, {self.size:,}B)'

@patch(as_prop=True)
def attachments(self:Message): return [Attachment(a, self._client) for a in self.get('attachments', [])]

# %% ../nbs/00_core.ipynb #acf92bc2
@patch
async def create_dm(self:DiscordClient, user_id):
    r = await self._req('POST', '/users/@me/channels', recipient_id=user_id)
    return Channel(r, self)

# %% ../nbs/00_core.ipynb #66bb1704
class User(DiscordObject):
    def __repr__(self): return f"User(id={self.id}, username={self.username!r})"

class Member(DiscordObject):
    def __repr__(self):
        name = self.nick or self.user['username']
        return f"Member(id={self.user['id']}, name={name!r}, joined={self.joined_at[:10]})"

class Members(list):
    def _repr_html_(self): return html_table(self, ("ID", "Name", "Joined", "Roles"), lambda m: (m.user['id'], m.nick or m.user['username'], m.joined_at[:10], len(m.roles)))

@patch
async def members(self:Guild, limit=100):
    data = await self('GET', f'/guilds/{self.id}/members', limit=limit)
    return self.coll('Member', data)

# %% ../nbs/00_core.ipynb #1a8f4ba5
def lbl(ch):
    l = "#" if ch.type==0 else "🔊"
    l += ch.name
    if t := getattr(ch, 'topic', ''): l += ': ' + t
    return l

@patch
async def tree(self:Guild, include_members=True, member_limit=1000):
    by_parent,cats = defaultdict(list),[None]
    for c in await self.channels():
        if c.type == 4: cats.append(c)
        elif c.type in (0,2): by_parent[c.parent_id].append(c)
    
    lines = [f"{self.name} [{self.id}]"]
    for cat in cats:
        lines.append(f"|-- {getattr(cat, 'name', 'Uncategorized')}")
        for ch in by_parent[getattr(cat, 'id', None)]:
            lines.append(f"|   |-- {lbl(ch)} [{ch.id}]")

    if include_members:
        lines.append("|-- Members")
        for m in await self.members(member_limit):
            u = m.user
            name = m.nick or u.get('global_name') or u['username']
            lines.append(f"|   |-- {name} [{u['id']}]")

    return "\n".join(lines)

# %% ../nbs/00_core.ipynb #4687437a
@patch
async def search_all(self:Guild, limit=500, delay=1.0, max_age_days=None, show=False, **kwargs):
    "Paginated search returning up to `limit` messages"
    all_msgs, offset = [], 0
    while len(all_msgs) < limit:
        msgs = await self.search(offset=offset, limit=25, **kwargs)
        if not msgs: break
        if max_age_days is not None:
            cutoff = datetime.now(timezone.utc) - timedelta(days=max_age_days)
            msgs = [m for m in msgs if datetime.fromisoformat(m.timestamp) > cutoff]
        all_msgs.extend(msgs)
        offset += 25
        if show: print(f'Fetched {len(msgs)} more')
        if len(msgs) < 25: break
        await asyncio.sleep(delay)
    return Messages(all_msgs[:limit])

@patch
@delegates(Guild.search_all, but=['channel_id'])
async def search_all(self:Channel, **kwargs):
    gld = await self.guild
    return await gld.search_all(channel_id=self.id, **kwargs)

# %% ../nbs/00_core.ipynb #beead147
@patch
async def delete(self:Message):
    "Delete this message"
    return await self('DELETE', f'/channels/{self.channel_id}/messages/{self.id}')

@patch
async def delete_message(self:Channel, message_id):
    "Delete a message by ID"
    return await self('DELETE', f'/channels/{self.id}/messages/{message_id}')

@patch
async def bulk_delete(self:Channel, message_ids):
    "Bulk delete messages (must be <14 days old)"
    return await self('POST', f'/channels/{self.id}/messages/bulk-delete', messages=[str(i) for i in message_ids])

# %% ../nbs/00_core.ipynb #1834fc2f
@patch
async def create_thread(self:Message, name):
    "Create a thread from this message"
    r = await self('POST', f'/channels/{self.channel_id}/messages/{self.id}/threads', name=name)
    return Channel(r, self)

@patch
async def thread(self:DiscordClient, thread_id):
    "Fetch a thread (which is a Channel)"
    return Channel(await self._req('GET', f'/channels/{thread_id}'), self)

# %% ../nbs/00_core.ipynb #05498e5a
@patch
async def _del_rotating(self:Channel, message_ids, delay=0.5, show=False):
    if show: print(f'Deleting {len(message_ids)} messages...')
    for i,mid in enumerate(message_ids):
        use_user = i % 2 == 1 and bool(self._client.user_token)
        try: await self('DELETE', f'/channels/{self.id}/messages/{mid}', use_user=use_user)
        except DiscordError as e:
            if e.args[0] == 10008: print(f"Already deleted: {mid}"); continue
            raise
        await asyncio.sleep(delay)
        if show: print('.', end='', flush=True)
    return len(message_ids)

# %% ../nbs/00_core.ipynb #a9c7d953
@patch
async def search_and_delete_all(self:Channel, content, delay=2, show=False, **kwargs):
    "Bulk delete recent msgs, individually delete older ones"
    assert content, "Must include content to search for"
    cutoff = datetime.now(timezone.utc) - timedelta(days=13)
    gld = await self.guild
    msgs = await gld.search_all(content=content, channel_id=self.id, show=show, **kwargs)
    seen = set()
    msgs = [m for m in msgs if m.id not in seen and not seen.add(m.id)]
    recent = [m for m in msgs if datetime.fromisoformat(m.timestamp) > cutoff]
    old = [m for m in msgs if datetime.fromisoformat(m.timestamp) <= cutoff]
    for i in range(0, len(recent), 20):
        ms = recent[i:i+20]
        if len(ms)>1: await self.bulk_delete([m.id for m in ms])
        else: await self._del_rotating([m.id for m in ms], show=show)
        if show: print(f'Bulk deleted {len(ms)}')
        await asyncio.sleep(delay)
    if old: await self._del_rotating([m.id for m in old], show=show, delay=delay)
    return len(msgs)

# %% ../nbs/00_core.ipynb #913993ce
class Webhook(DiscordObject):
    def __repr__(self): return f"Webhook(id={self.id}, name={self.name!r})"

class Webhooks(list):
    def _repr_html_(self): return html_table(self, ("ID", "Name", "Channel"), lambda w: (w.id, w.name, w.channel_id))

@patch
async def webhooks(self:Channel):
    "List this channel's webhooks"
    return self.coll('Webhook', await self('GET', f'/channels/{self.id}/webhooks'))

@patch
async def webhooks(self:Guild):
    "List all webhooks in this guild"
    return self.coll('Webhook', await self('GET', f'/guilds/{self.id}/webhooks'))

@patch
async def webhook(self:DiscordClient, webhook_id):
    "Fetch a webhook by ID"
    return Webhook(await self._req('GET', f'/webhooks/{webhook_id}'), self)

# %% ../nbs/00_core.ipynb #54e21572
@patch
async def create_webhook(self:Channel, name):
    "Add webhook `name` to Channel"
    r = await self('POST', f'/channels/{self.id}/webhooks', name=name)
    return Webhook(r, self)

# %% ../nbs/00_core.ipynb #d346b1f4
@patch
async def edit(self:Webhook, name=None, channel_id=None):
    "Modify this webhook's `name` or move it to `channel_id`"
    return Webhook(await self('PATCH', f'/webhooks/{self.id}', name=name, channel_id=channel_id), self._parent)

@patch
async def delete(self:Webhook):
    "Delete this webhook"
    return await self('DELETE', f'/webhooks/{self.id}')

@patch
async def send(self:Webhook, content='', username=None, avatar_url=None):
    "Execute this webhook, optionally overriding the display `username`/`avatar_url`"
    r = await self('POST', f'/webhooks/{self.id}/{self.token}?wait=true', content=content, username=username, avatar_url=avatar_url)
    return Message(r, self)
