"""Real-time Discord events over the WebSocket gateway

Docs: https://AnswerDotAI.github.io/cordslite/gateway.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_gateway.ipynb.

# %% auto #0
__all__ = ['evt_typs', 'GatewayClient', 'Op', 'Event']

# %% ../nbs/01_gateway.ipynb #88065cca
from .core import *
from fastcore.utils import *

import asyncio,httpx,json,os,random
import websockets, websockets.asyncio.client

# %% ../nbs/01_gateway.ipynb #f87f7e5d
class GatewayClient:
    def __init__(self, intents, client, token=None):
        self.intents,self.dc = intents,client
        self.token = token or os.environ['DISCORD_BOT_TOKEN']
        self.ws = self.hb_int = self.session_id = self.seq = None
        self.running = False
        self._tries = 0
        gw_info = httpx.get(f'{client.base_url}/gateway/bot', headers={'Authorization': f'Bot {self.token}'}).json()
        if 'url' not in gw_info: raise ConnectionError(f"Gateway auth failed: {gw_info.get('message', gw_info)}")
        self.url = f"{gw_info['url']}?v=10&encoding=json"
        self.handlers = {'READY': self.on_rdy}
    
    async def on_rdy(self, evt):
        self.session_id, self.user_id, = evt['session_id'], evt['user']['id']
        self.resume_url = evt['resume_gateway_url'] + '?v=10&encoding=json' if 'resume_gateway_url' in evt else self.url
        
    def __repr__(self): return f"GatewayClient({self.intents=}, {self.url=})"

# %% ../nbs/01_gateway.ipynb #c9277a75
class Op(AttrDict):
    def __repr__(self): return f"Op(op={self.op}, d={self.d})"
    @classmethod
    def identify(cls, token, intents):
        d = AttrDict(token=token, intents=intents, properties=dict(os='linux',browser='discord_wrapper', device='discord_wrapper'))
        return cls(op=2, d=d)
    @classmethod
    def heartbeat(cls, seq): return cls(op=1, d=seq)
    @classmethod
    def resume(cls, token, session_id, seq): return cls(op=6, d=AttrDict(token=token, session_id=session_id, seq=seq))

# %% ../nbs/01_gateway.ipynb #5e0b8f9f
evt_typs = {'MESSAGE_CREATE': Message,
            'MESSAGE_UPDATE': Message,
            'MESSAGE_DELETE': Message,
            'GUILD_CREATE': Guild,
            'CHANNEL_CREATE': Channel}

class Event(DiscordObject):
    def __init__(self, data, client):
        super().__init__(data, client)
        typ = evt_typs.get(self.t)
        self.d = typ(self.d, client) if typ else self.d
    @property
    def type(self): return self.t
    @property
    def seq(self): return self.s
    def __repr__(self): return f"Event({self.op=}, {self.type=}, {self.seq=})"

@patch
async def send(self:websockets.asyncio.client.ClientConnection, msg, **kw):
    if isinstance(msg, dict): msg = json.dumps(msg)
    return await self._orig_send(msg, **kw)

# %% ../nbs/01_gateway.ipynb #32dcd695
@patch
async def recv_evt(self:GatewayClient):
    evt = Event(json.loads(await self.ws.recv()), self.dc)
    if evt.op == 0 and evt.seq: self.seq,self._tries = evt.seq,0
    return evt

# %% ../nbs/01_gateway.ipynb #34218c7b
@patch
def on(self:GatewayClient, event_type, handler): self.handlers[event_type] = handler

# %% ../nbs/01_gateway.ipynb #fa026ae6
@patch
async def _hb(self:GatewayClient):
    await asyncio.sleep(self.hb_int / 1_000 * random.random()) # jitter
    while self.running:
        self._got_ack = False
        try: await self.ws.send(Op.heartbeat(self.seq))
        except Exception: return
        await asyncio.sleep(self.hb_int / 1_000)
        if not self._got_ack: return await self.ws.close(code=4000)

@patch
async def _reconnect(self:GatewayClient, resume=False):
    resume = resume and bool(self.session_id)
    code, url = (4000, self.resume_url) if resume else (1000, self.url)
    if not resume: self.session_id = None
    try: await self.ws.close(code=code)
    except Exception: pass
    while self.running:
        await asyncio.sleep(min(2 ** self._tries, 60))
        self._tries += 1
        try:
            self.ws = await websockets.connect(url, max_size=None)
            return
        except OSError as e: print('gateway reconnect failed:', repr(e))

@patch
async def _listen(self:GatewayClient):
    while self.running:
        try:
            evt = await self.recv_evt()
            if self.debug: print('DEBUG: Received Opcode:', evt.op)
            if evt.op == 10:
                self.hb_int = evt.d['heartbeat_interval']
                if hasattr(self, '_hb_task') and self._hb_task: self._hb_task.cancel()
                self._hb_task = asyncio.create_task(self._hb())
                if self.session_id: await self.ws.send(Op.resume(self.token, self.session_id, self.seq))
                else: await self.ws.send(Op.identify(self.token, self.intents))
            elif evt.op == 0 and evt.type in self.handlers: asyncio.create_task(self.handlers[evt.type](evt.d))
            elif evt.op == 11: self._got_ack = True
            elif evt.op == 1: await self.ws.send(Op.heartbeat(self.seq))
            elif evt.op == 7: await self._reconnect(resume=True)
            elif evt.op == 9: await self._reconnect(resume=evt.d)
        except websockets.exceptions.ConnectionClosed as e:
            if not self.running: break
            print(f'gateway closed: {e.code} {e.reason}')
            if e.code in (4004, 4010, 4011, 4012, 4013, 4014): # fatal: bad token/shard/intents
                self.running = False
                break
            await self._reconnect(resume=e.code not in (4007, 4009))
            continue
        except Exception as e:
            print('gateway listen error:', repr(e))
            await self._reconnect(resume=True)
            continue

# %% ../nbs/01_gateway.ipynb #90eff6e7
@patch
async def start(self:GatewayClient, debug=False):
    self.debug = debug
    self.running = True
    self.ws = await websockets.connect(self.url, max_size=None)
    self._listen_task = asyncio.create_task(self._listen())

# %% ../nbs/01_gateway.ipynb #ac87d816
@patch
async def stop(self:GatewayClient):
    self.running = False
    for t in (self._hb_task, self._listen_task):
        if t: t.cancel()
    if self.ws: await self.ws.close()
